CREATE TABLE USERS (
  USERNAME VARCHAR(250) NOT NULL PRIMARY KEY,
  PASSWORD VARCHAR(512) NOT NULL,
  ENABLED BOOLEAN NOT NULL
);

CREATE TABLE AUTHORITIES (
  USERNAME VARCHAR(250) NOT NULL,
  AUTHORITY VARCHAR(250) NOT NULL
);